### ISSUE TITLE
插件很棒，想提几个改进建议

### ISSUE THREAD

**Issue by Seifon** [imzhoukunqiang/sql-parser#1]
1.执行结果，也能转换出来。

2.转换结果，自动放入剪切板

3.转换结果尽量不要弹窗，要是可以在控制台里面显示会更好。或者弹出框不要自动消失，而是弄个关闭按钮。

希望作者能够改进，非常感谢了！

**Comment by imzhoukunqiang** [comment]
嗯。。

第一点我不是很理解你的意思。

关于第二点，其实点击转换的时候已经自动帮你把结果复制到剪切板了。

3，这个插件初始的时候的确是弹窗，点击关闭按钮才消失的。由于我没有找到好看的组件，加上后期直接将结果复制到剪切板了，所以这个弹窗也只是给你一个反馈，并不是要到弹窗里面去复制结果。

**Comment by imzhoukunqiang** [comment]
嗯。。

第一点我不是很理解你的意思。

关于第二点，其实点击转换的时候已经自动帮你把结果复制到剪切板了。

3，这个插件初始的时候的确是弹窗，点击关闭按钮才消失的。由于我没有找到好看的组件，加上后期直接将结果复制到剪切板了，所以这个弹窗也只是给你一个反馈，并不是要到弹窗里面去复制结果。
